// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.11.4
// source: server_msg.proto

package fcmd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqServerRegist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GWId uint32 `protobuf:"varint,1,opt,name=GWId,proto3" json:"GWId,omitempty"`
}

func (x *ReqServerRegist) Reset() {
	*x = ReqServerRegist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqServerRegist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqServerRegist) ProtoMessage() {}

func (x *ReqServerRegist) ProtoReflect() protoreflect.Message {
	mi := &file_server_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqServerRegist.ProtoReflect.Descriptor instead.
func (*ReqServerRegist) Descriptor() ([]byte, []int) {
	return file_server_msg_proto_rawDescGZIP(), []int{0}
}

func (x *ReqServerRegist) GetGWId() uint32 {
	if x != nil {
		return x.GWId
	}
	return 0
}

type RetServerRegist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State uint32 `protobuf:"varint,1,opt,name=State,proto3" json:"State,omitempty"`
}

func (x *RetServerRegist) Reset() {
	*x = RetServerRegist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetServerRegist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetServerRegist) ProtoMessage() {}

func (x *RetServerRegist) ProtoReflect() protoreflect.Message {
	mi := &file_server_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetServerRegist.ProtoReflect.Descriptor instead.
func (*RetServerRegist) Descriptor() ([]byte, []int) {
	return file_server_msg_proto_rawDescGZIP(), []int{1}
}

func (x *RetServerRegist) GetState() uint32 {
	if x != nil {
		return x.State
	}
	return 0
}

type ServiceNodeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Addr string `protobuf:"bytes,2,opt,name=Addr,proto3" json:"Addr,omitempty"`
}

func (x *ServiceNodeInfo) Reset() {
	*x = ServiceNodeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_msg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceNodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceNodeInfo) ProtoMessage() {}

func (x *ServiceNodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_server_msg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceNodeInfo.ProtoReflect.Descriptor instead.
func (*ServiceNodeInfo) Descriptor() ([]byte, []int) {
	return file_server_msg_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceNodeInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ServiceNodeInfo) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type ServiceGroupInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service Service            `protobuf:"varint,1,opt,name=Service,proto3,enum=fcmd.Service" json:"Service,omitempty"`
	Nodes   []*ServiceNodeInfo `protobuf:"bytes,2,rep,name=Nodes,proto3" json:"Nodes,omitempty"`
	LBType  uint32             `protobuf:"varint,3,opt,name=LBType,proto3" json:"LBType,omitempty"`
}

func (x *ServiceGroupInfo) Reset() {
	*x = ServiceGroupInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_msg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceGroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceGroupInfo) ProtoMessage() {}

func (x *ServiceGroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_server_msg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceGroupInfo.ProtoReflect.Descriptor instead.
func (*ServiceGroupInfo) Descriptor() ([]byte, []int) {
	return file_server_msg_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceGroupInfo) GetService() Service {
	if x != nil {
		return x.Service
	}
	return Service_ServiceTypeNone
}

func (x *ServiceGroupInfo) GetNodes() []*ServiceNodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ServiceGroupInfo) GetLBType() uint32 {
	if x != nil {
		return x.LBType
	}
	return 0
}

type ReqLoadServiceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SelfService Service `protobuf:"varint,1,opt,name=SelfService,proto3,enum=fcmd.Service" json:"SelfService,omitempty"` //当前服务
}

func (x *ReqLoadServiceInfo) Reset() {
	*x = ReqLoadServiceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_msg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqLoadServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqLoadServiceInfo) ProtoMessage() {}

func (x *ReqLoadServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_server_msg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqLoadServiceInfo.ProtoReflect.Descriptor instead.
func (*ReqLoadServiceInfo) Descriptor() ([]byte, []int) {
	return file_server_msg_proto_rawDescGZIP(), []int{4}
}

func (x *ReqLoadServiceInfo) GetSelfService() Service {
	if x != nil {
		return x.SelfService
	}
	return Service_ServiceTypeNone
}

type RetLoadlServiceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceGroup []*ServiceGroupInfo `protobuf:"bytes,1,rep,name=ServiceGroup,proto3" json:"ServiceGroup,omitempty"`
}

func (x *RetLoadlServiceInfo) Reset() {
	*x = RetLoadlServiceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_msg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetLoadlServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetLoadlServiceInfo) ProtoMessage() {}

func (x *RetLoadlServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_server_msg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetLoadlServiceInfo.ProtoReflect.Descriptor instead.
func (*RetLoadlServiceInfo) Descriptor() ([]byte, []int) {
	return file_server_msg_proto_rawDescGZIP(), []int{5}
}

func (x *RetLoadlServiceInfo) GetServiceGroup() []*ServiceGroupInfo {
	if x != nil {
		return x.ServiceGroup
	}
	return nil
}

var File_server_msg_proto protoreflect.FileDescriptor

var file_server_msg_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x66, 0x63, 0x6d, 0x64, 0x1a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x25, 0x0a, 0x0f, 0x52, 0x65, 0x71, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x47, 0x57,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x47, 0x57, 0x49, 0x64, 0x22, 0x27,
	0x0a, 0x0f, 0x52, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x35, 0x0a, 0x0f, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x41, 0x64,
	0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x41, 0x64, 0x64, 0x72, 0x22, 0x80,
	0x01, 0x0a, 0x10, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x27, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x66, 0x63, 0x6d, 0x64, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x52, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2b, 0x0a, 0x05,
	0x4e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x66, 0x63,
	0x6d, 0x64, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x05, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x4c, 0x42, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x4c, 0x42, 0x54, 0x79, 0x70,
	0x65, 0x22, 0x45, 0x0a, 0x12, 0x52, 0x65, 0x71, 0x4c, 0x6f, 0x61, 0x64, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2f, 0x0a, 0x0b, 0x53, 0x65, 0x6c, 0x66, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x66,
	0x63, 0x6d, 0x64, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x0b, 0x53, 0x65, 0x6c,
	0x66, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x51, 0x0a, 0x13, 0x52, 0x65, 0x74, 0x4c,
	0x6f, 0x61, 0x64, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x3a, 0x0a, 0x0c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x66, 0x63, 0x6d, 0x64, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x42, 0x08, 0x5a, 0x06, 0x2e,
	0x2f, 0x66, 0x63, 0x6d, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_msg_proto_rawDescOnce sync.Once
	file_server_msg_proto_rawDescData = file_server_msg_proto_rawDesc
)

func file_server_msg_proto_rawDescGZIP() []byte {
	file_server_msg_proto_rawDescOnce.Do(func() {
		file_server_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_msg_proto_rawDescData)
	})
	return file_server_msg_proto_rawDescData
}

var file_server_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_server_msg_proto_goTypes = []interface{}{
	(*ReqServerRegist)(nil),     // 0: fcmd.ReqServerRegist
	(*RetServerRegist)(nil),     // 1: fcmd.RetServerRegist
	(*ServiceNodeInfo)(nil),     // 2: fcmd.ServiceNodeInfo
	(*ServiceGroupInfo)(nil),    // 3: fcmd.ServiceGroupInfo
	(*ReqLoadServiceInfo)(nil),  // 4: fcmd.ReqLoadServiceInfo
	(*RetLoadlServiceInfo)(nil), // 5: fcmd.RetLoadlServiceInfo
	(Service)(0),                // 6: fcmd.Service
}
var file_server_msg_proto_depIdxs = []int32{
	6, // 0: fcmd.ServiceGroupInfo.Service:type_name -> fcmd.Service
	2, // 1: fcmd.ServiceGroupInfo.Nodes:type_name -> fcmd.ServiceNodeInfo
	6, // 2: fcmd.ReqLoadServiceInfo.SelfService:type_name -> fcmd.Service
	3, // 3: fcmd.RetLoadlServiceInfo.ServiceGroup:type_name -> fcmd.ServiceGroupInfo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_server_msg_proto_init() }
func file_server_msg_proto_init() {
	if File_server_msg_proto != nil {
		return
	}
	file_service_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_server_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqServerRegist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetServerRegist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_msg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceNodeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_msg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceGroupInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_msg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqLoadServiceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_msg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetLoadlServiceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_msg_proto_goTypes,
		DependencyIndexes: file_server_msg_proto_depIdxs,
		MessageInfos:      file_server_msg_proto_msgTypes,
	}.Build()
	File_server_msg_proto = out.File
	file_server_msg_proto_rawDesc = nil
	file_server_msg_proto_goTypes = nil
	file_server_msg_proto_depIdxs = nil
}
